### ISSUE TITLE
Unable to run any mix cmd using build-elixir

### ISSUE THREAD

**Issue by fboyer** [AtomBuild/atom-build-elixir#7] opened 2016-04-21 15:51 UTC
Hi,

I am currently using the following:
- OS: Windows 7 Enterprise
- Atom version: 1.7.2
- build version: 0.59.0
- build-elixir version: 0.6.0

I've attempted to use this package in the last few days but have been unable to get it running. It seems that it cannot find `elixir.bat` see the following output message:

```
'"C:\code\elixir\test_project\\elixir.bat"' is not recognized as an internal or external command,
operable program or batch file.
```

I've validated that elixir is in my path:

```
λ echo %PATH%
C:\tools\cmder\bin;C:\tools\cmder\vendor\msysgit\bin;C:\tools\cmder\vendor\msysgit\mingw\bin;C:\tools\cmder\vendor\msysgit\cmd;C:\tools\cmder\vendor\msysgit\share\vim\vim74;C:\tools\cmder;C:\tools\cmder\bin;C:\tools\cmder\vendor\msysgit\bin;C:\tools\cmder\vendor\msysgit\mingw\bin;C:\tools\cmder\vendor\msysgit\cmd;C:\tools\cmder\vendor\msysgit\share\vim\vim74;C:\tools\cmder;C:\tools\cmder\vendor\conemu-maximus5\ConEmu;C:\tools\cmder\vendor\conemu-maximus5;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\SlikSvn\bin;C:\Program Files\TortoiseSVN\bin;C:\ProgramData\chocolatey\bin;C:\tools\go\bin;C:\Program Files\nodejs\;C:\Program Files\erl7.3\bin;C:\Program Files (x86)\Elm Platform\0.16\bin;C:\tools\mingw64\bin;C:\ProgramData\chocolatey\lib\Elixir\bin;C:\Users\fredericb\AppData\Roaming\local\bin;C:\Users\fredericb\AppData\Local\atom\bin;C:\code\go\bin;C:\code\elm\bin;C:\Users\fredericb\AppData\Roaming\npm;C:\Users\fredericb\AppData\Local\Pandoc;
```

```
λ elixir.bat --version
Erlang/OTP 18 [erts-7.3] [64-bit] [smp:4:4] [async-threads:10]

Elixir 1.2.4
```

Any idea what could be wrong? I am currently running the following:

Thanks!

**Comment by noseglid** [comment] 2016-04-21 19:23
Can you run `"C:\code\elixir\test_project\\elixir.bat"` in a console?
Also, there's a double backslash before `elixir.bat`. Could that be something?

**Comment by fboyer** [comment] 2016-04-22 18:18
The command line being run is not valid, even if I run it manually. The elixir.bat command can actually be found in the following folder: `C:\ProgramData\chocolatey\lib\elixir\bin\`. (Also, I did see this double backslash which seemed weird but I am unsure how it got there.)

The thing is the package install is in its default state (other than the build package having "build on save" enabled) so I do not know how the package built up the `"C:\code\elixir\test_project\\elixir.bat"` command.

**Comment by fboyer** [comment] 2016-04-25 19:09
FYI, I've tested the package on my Mac and this issue does not seem to occur. Everything builds fine after a clean/default state install of the package.

**Comment by fboyer** [comment] 2016-04-29 18:31
After a bit of skimming through the `build` and `build-elixir` package code, I managed to get this to work under Windows by changing `sh: false` to `sh: true`. 

This seems to work due to the fact that it does not attempt to build the command using the `cwd`. (I am not saying this is the right way to fix this issue but it might give a hint as to why it does not work under Windows, at least for me.)

**Comment by noseglid** [comment] 2016-04-29 19:11
Wait a minute. Where does `elixir.bat` come from?
This plugin runs `mix.bat` if under window [as seen here](https://github.com/AtomBuild/atom-build-elixir/blob/master/lib/elixir.js#L20).

How are you running this really? Do you have a custom file in your project too (E.g. `.atom-build.json` or friends?)

**Comment by fboyer** [comment] 2016-04-30 17:18
I have no idea as this is the default behavior on a fresh install. I tried on my Windows laptop at work and on my desktop at home and the same command is run by default. I have no custom .atom-build.json in my project. See the following screenshot: 
![image](https://cloud.githubusercontent.com/assets/5251551/14937466/e400851a-0ed5-11e6-8f56-e42e902d84e1.png)

**Comment by noseglid** [comment] 2016-04-30 17:59
If you open up `mix.bat`, what's in it?

**Comment by fboyer** [comment] 2016-04-30 19:47
The content of the file is the following:
`@if defined ELIXIR_CLI_ECHO (@echo on) else  (@echo off)
call "%~dp0\elixir.bat" "%~dp0\mix" %*`

The batch files come from the official precompiled package: [https://github.com/elixir-lang/elixir/releases/download/v1.2.4/Precompiled.zip](https://github.com/elixir-lang/elixir/releases/download/v1.2.4/Precompiled.zip).

**Comment by noseglid** [comment] 2016-05-01 08:13
So that's where it comes from. I'm guessing `~dp0` is not setup correctly. If this were unix that would be the home folder of user `dp0`, I don't know about windows though.

Closing this as it has nothing to do with this package. It is successfully running `mix.exs`, which seems to be incorrectly installed.

**Closed as completed by noseglid** 2016-05-01 08:13 UTC

**Comment by allansson** [comment] 2016-06-28 14:35
I have the same issue and spent some time trying to figure the problem out, and I managed to track the issue down to the `cross-spawn-async` module used by `atom-build` (and perhaps, ultimately, to Windows itself).

When trying to execute e.g. `mix.bat compile`, 'cross-spawn-async' will spawn a `cmd.exe` with the following command:

``` batch
cmd.exe /s /c ""mix.bat" "compile""
```

The problem is that the batch file has been escaped twice, which means that the the %0 argument (equivalent to $0 in linux) becomes the escaped `"mix.bat"` instead of plain `mix.bat`. 

It seems that Windows cannot resolve the path to the batch file using `%~dp0` when the name of the batch file has been escaped. Proving this is as simple as trying to execute the following in any other folder than where the `mix.bat` is located:

``` batch
"mix.bat"
```

Flipping `sh` to true will avoid the logic to escape arguments used by `cross-spawn-async`, which explains why it started working for @fboyer after doing it.
